### ISSUE TITLE
Allow to set the SKU of a product

### ISSUE THREAD

**Issue by avstudnitz** [tddwizard/magento2-fixtures#2]
You can set the email address for customers, so you should be able to set the sku for products. This makes it easier to set relations between products, like upselling.

**Comment by schmengler** [comment]
This already has been added in [#f80fe9b](https://github.com/tddwizard/magento2-fixtures/commit/f80fe9b9b784918af21a13b453a8f0ae2355a808)

https://github.com/tddwizard/magento2-fixtures/blob/f80fe9b9b784918af21a13b453a8f0ae2355a808/src/Catalog/ProductBuilder.php#L104-L108
