### ISSUE TITLE
phpunit4.php file breaks PHPStorm autocomplete for real TestCase

### ISSUE THREAD

**Issue by bartoszkubicki** [tddwizard/magento2-fixtures#30]
Subject touches file `vendor/tddwizard/magento2-fixtures/src/phpunit4.php`. Is there any chance to drop support for Magento 2.1 (We have 2.3 right now, and I bet if there is still 2.1 installation I don't think they have unit tests)? Or any composer trick or sth to exclude this file from installation? Composer patch can't be used, as it gets complicated for modifying `composer.json` file by composer itself. For now, it is enough to comment out whole `if` statement inside this file, but of course it is not the way.

**Comment by Tjitse-E** [comment]
@bartoszkubicki  I had the same problem, what I did was: right click on phpunit4.php in PHPstorm and click 'mark as plain text'. This will fix the autocomplete without any code modifications.

**Comment by bartoszkubicki** [comment]
Tip from @Tjitse-E solves problem. For me it is enough. I would suggest adding this tip to `README.md` or sth.
