### ISSUE TITLE
PHP Version Requirement

### ISSUE THREAD

**Issue by mam08ixo** [tddwizard/magento2-fixtures#38]
Magento 2.2 runs on PHP 7.0 to PHP 7.2
Magento 2.3 runs on PHP 7.1 to PHP 7.3

With the update 24e773d I can no longer install the package on three out of six possible combinations. In my opinion, this defeats the purpose of this library, which is especially helpful for executing cross-version tests for the more unpopular combinations (the ones you usually do not develop on).

Please revert the PHP version requirement, thanks.

**Comment by schmengler** [comment]
So be it...
