### ISSUE TITLE
Support bundle products - was: Make cartbuilder able to use actual products from the database?

### ISSUE THREAD

**Issue by amenk** [tddwizard/magento2-fixtures#4]
I have to test with a pretty complex bundle product, so I imported the production database to the integration database, I think that is seems to be okay.

No I want to put this product into the cart during cart builder.

I would add a withProductInstance() method ... 

Does this make sense and a pull request would be merged?

**Comment by amenk** [comment]
I see that I can already load products .. but I have to support bundle products ...

**Comment by schmengler** [comment]
Does #5 already solve the issue? If not, how would a convenient interface look like to add bundle products?

**Comment by amenk** [comment]
It basically solves the issue ... I do not really know how a convenient interface could look like .. these bundle options etc. are not easy to put into an array in Magento.

**Comment by schmengler** [comment]
True. An object oriented interface would be nice but it's not going to be
easy. So for now, the custom request object should be enough
