### ISSUE TITLE
Improvements for AddressBuilder

### ISSUE THREAD

**Issue by bartoszkubicki** [tddwizard/magento2-fixtures#45]
Hello @schmengler , 

I would like to propose improvent for [address builder](https://github.com/tddwizard/magento2-fixtures/blob/master/src/Customer/AddressBuilder.php). In Poland, where I live and work if we build store for B2B clients it is really common to use vat id heavily. Lately we have to add validation for vat id and make it required. I had problems with integration tests, beacause by using builder I have no access to address object and I couldn't set vat id, so I had to wrap builder with mine. 

I would like to add vat id with some dummy value [here](https://github.com/tddwizard/magento2-fixtures/blob/32fb867018c117879e8daf0d15307e2fd2f2959b/src/Customer/AddressBuilder.php#L68) and add function allowing setting this value manually. What do you think? If you agree I will prepare PR.

**Comment by mam08ixo** [comment]
I would rather not change the factory method but only add the setter. I don't think adding a VAT ID by default is useful. With the additional setter, you can easily add the property to faker-generated addresses like this:

```php
AddressBuilder::anAddress(null, 'pl_PL')->withVatId('PL123456')
```

When creating the PR, then please also add tests to assert that the VAT ID has the expected value on the built address. Thank you!

**Comment by schmengler** [comment]
Agree @mam08ixo , a VAT ID by default could become a problem for B2C shops for example. But I can imagine an additional factory method like `aCompanyAddress()` with a `$vatId` parameter. The parameter could have a default value of null and take a dummy from Faker in that case. Would that be useful for you @bartoszkubicki ?

**Comment by bartoszkubicki** [comment]
Solution proposed by @mam08ixo is really good I could go this way. But @schmengler solution is even better, because its much more expressive.

**Comment by schmengler** [comment]
@bartoszkubicki A PR would be great

**Comment by schmengler** [comment]
Thanks again @bartoszkubicki !
