### ISSUE TITLE
Relaxing fzaninotto/faker dependency requirements

### ISSUE THREAD

**Issue by bartoszkubicki** [tddwizard/magento2-fixtures#46]
Hello @schmengler 
I am using your awesome library in a few projects. I was able to install latest version (0.10.0) on Magento 2.3.5 and everything works excellent.
When I switched to another installation (Magento 2.3.3) I was stuck on version 0.8.0, because of dependency `fzaninotto/faker`. It blocks update. You require version `^1.9.0` and magento 2.3.5 has it already installed with version 1.8.0. It would be great to relax it, because upgrade of magento is not always possible just in time. Clients have different upgrade policies or just want to pay for something other. I miss useful order and invoice builders on 0.8.0  version :)

**Comment by mam08ixo** [comment]
Please doublecheck what locks `fzaninotto/faker` to version 1.8.0 in your project. In a vanilla M2 installation, I can only see `magento/magento2-functional-testing-framework` requiring the package in `^1.6` – which includes version 1.9.0 so there should not be a problem.
