### ISSUE TITLE
Question: returning object from fixtures

### ISSUE THREAD

**Issue by lfolco** [tddwizard/magento2-fixtures#66]
I noticed that a lot of the `Fixture` objects return properties, but not the actual object created. Is there a reason for that, or would you accept a PR that returns them?

Example: `https://github.com/tddwizard/magento2-fixtures/blob/master/src/Sales/OrderFixture.php` would have a method, `getOrder()` that returns `$this->order`.

**Comment by schmengler** [comment]
Originally I thought I would not need the objects but reality has proven me wrong already :grin: I'll accept a PR to add methods like that!
