### ISSUE TITLE
Can't install tddwizard in php8.1

### ISSUE THREAD

**Issue by rohit-jiva-ag** [tddwizard/magento2-fixtures#77]
I just try today by installing tddwizard in magento2.4.4 and php version 8.1

i just seen update of yesterday in github. so today i have checked but not able to install.

It try to install by this command :

composer require --dev tddwizard/magento2-fixtures
composer require tddwizard/magento2-fixtures

**Comment by schmengler** [comment]
Please post the error message of composer

**Comment by rohit-jiva-ag** [comment]
Hi @schmengler 
Thank you for help.
I'm getting following error white running composer require.
php version 8.1.4
magento version 2.4.4

`composer require --dev tddwizard/magento2-fixtures
Info from https://repo.packagist.org: #StandWithUkraine

                                                                                                                                 
  [InvalidArgumentException]                                                                                                     
  Package tddwizard/magento2-fixtures has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - tddwizard/magento2-fixtures 1.1.0 requires php ^7.1 which does not match your installed version 8.1.4.                     
                                                                                                                                 

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...`

Thanks

**Comment by schmengler** [comment]
Understood. I tagged version 1.1.1 with PHP 8.1 compatibility but packagist was not updated yet. Please try again

**Comment by rohit-jiva-ag** [comment]
Hi @schmengler 

Currently getting different error currently : 

composer require --dev tddwizard/magento2-fixtures

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.1 for tddwizard/magento2-fixtures
./composer.json has been updated
Running composer update tddwizard/magento2-fixtures
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tddwizard/magento2-fixtures v1.1.1 requires fzaninotto/faker ^1.8.0 -> satisfiable by fzaninotto/faker[v1.8.0, v1.9.0, v1.9.1, v1.9.2].
    - tddwizard/magento2-fixtures 1.1.0 requires php ^7.1 -> your php version (8.1.4) does not satisfy that requirement.
    - fzaninotto/faker[v1.8.0, ..., v1.9.2] require php ^5.3.3 || ^7.0 -> your php version (8.1.4) does not satisfy that requirement.
    - Root composer.json requires tddwizard/magento2-fixtures ^1.1 -> satisfiable by tddwizard/magento2-fixtures[1.1.0, v1.1.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require tddwizard/magento2-fixtures:*" to figure out if any version is installable, or "composer require tddwizard/magento2-fixtures:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by schmengler** [comment]
Oh yes, Faker is not maintained anymore and does not support PHP 8. We need to remove or replace this dependency...

I made a mistake when configuring the test Github Action for PHP 8.1 and it actually ran on PHP 7.4 too so I didn't notice :see_no_evil:

**Comment by rohit-jiva-ag** [comment]
thanks @schmengler

**Comment by rohit-jiva-ag** [comment]
Hi @schmengler 
Thanks for looking into this, Is any possibility to release compatible version in this week?

**Comment by chiragd-evrig** [comment]
@schmengler Instead of removing faker in #79 we can also replace it with https://github.com/fakerphp/faker that is what laravel is using right now

**Comment by schmengler** [comment]
@chiragd-evrig thanks for bringing it to my attention, I wasn't aware of an active fork. That should make the backwards compatible replacement easy :+1:

**Comment by schmengler** [comment]
=> #81
